name: Build Installers

on:
  push:
    branches:
      - test-windows-installer
    # Run Action only when /docker is pushed to
#    paths:
#      - 'docker/**'
  workflow_dispatch:

jobs:
  windows-installer:
    name: Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Installer
      run: docker run -v $GITHUB_WORKSPACE/docker:/src/ danleyb2/pyinstaller-windows "pyinstaller platerec_installer.spec -F"
    - uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer-unsigned
        path: docker/dist

  linux-installer:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Installer
      run: docker run -v $GITHUB_WORKSPACE/docker:/src/ cdrx/pyinstaller-linux "pyinstaller platerec_installer.spec -F"
    - uses: actions/upload-artifact@v4
      with:
        name: PlateRecognizer-Installer-Linux
        path: docker/dist/PlateRecognizer-Installer

  # sign-installer:
  #   name: Sign
  #   runs-on: windows-latest
  #   needs: windows-installer
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: Windows-Installer-unsigned
  #         path: dist

  #     - uses: DanaBear/code-sign-action@98c79121b376beab8d6a9484f445089db4461bca
  #       with:
  #         certificate: '${{ secrets.CERTIFICATE }}'
  #         password: '${{ secrets.PASSWORD }}'
  #         certificatesha1: '${{ secrets.CERTIFICATE_SHA1 }}'
  #         timestampUrl: '${{ secrets.TIMESTAMP_URL }}'
  #         folder: dist
  #         recursive: true
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: PlateRecognizer-Installer-Windows
  #         path: dist

  test-windows-installer:
    runs-on: windows-latest
    needs: windows-installer
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Windows-Installer-unsigned
          path: dist
      - run: |
          tree /F D:\a\deep-license-plate-recognition\deep-license-plate-recognition\dist
          
      - name: Test installer Startup
        id: test-executable
        run: |
          # Run your executable in the background
          Start-Process -FilePath .\dist\Windows-Installer-unsigned -NoNewWindow

          # Wait for the executable to start (adjust the sleep duration if needed)
          Start-Sleep -Seconds 5

          # Make a curl-like request to localhost:8050
          $response = Invoke-RestMethod -Uri http://localhost:8050

          # Check if the status code is 200
          if ($response.StatusCode -eq 200) {
            Write-Output "Test Passed: Status code is 200"
          } else {
            Write-Error "Test Failed: Unexpected status code $($response.StatusCode)"
            exit 1
          }

  mac-installer:
    runs-on: macos-latest
    name: MacOS
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.7.12
    - name: Build Installer
      run: |
        cd docker
        pip install -r requirements.txt pyinstaller==4.9
        pyinstaller platerec_installer.spec -F
        chmod -R +x dist
    - uses: actions/upload-artifact@v4
      with:
        name: PlateRecognizer-Installer-MacOS
        path: docker/dist/*

